import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer'
import type { ReportData, VendorRating } from './EventReportBuilder'

try {
  Font.register({
    family: 'Plus Jakarta Sans',
    fonts: [
      { src: 'https://fonts.gstatic.com/s/plusjakartasans/v8/LDIoaomQNQcsA88c7O9yZ4KMCoOg4Ko20yw.ttf', fontWeight: 400 },
      { src: 'https://fonts.gstatic.com/s/plusjakartasans/v8/LDIoaomQNQcsA88c7O9yZ4KMCoOg4Ko70y4.ttf', fontWeight: 700 },
    ],
  })
} catch { /* fallback to Helvetica */ }

const FONT = 'Plus Jakarta Sans'

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: FONT, color: '#1a1a1a', backgroundColor: '#ffffff' },
  title: { fontSize: 20, fontWeight: 'bold', marginBottom: 4, color: '#1a1a1a' },
  subtitle: { fontSize: 10, color: '#666', marginBottom: 20 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 13, fontWeight: 'bold', marginBottom: 6, borderBottom: '1 solid #ccc', paddingBottom: 3 },
  row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 3 },
  label: { color: '#666' },
  value: { fontWeight: 'bold' },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 8, color: '#999', textAlign: 'center' },
  phaseItem: { flexDirection: 'row', alignItems: 'center', marginBottom: 2 },
  phaseDot: { width: 10, height: 10, borderRadius: 5, marginRight: 6 },
  ratingStar: { color: '#D4A017', fontSize: 10 },
  headerMeta: { fontSize: 9, color: '#888', marginBottom: 16 },
})

interface PdfDocProps {
  data: ReportData
  vendorRatings: VendorRating[]
  type: 'internal' | 'client'
  plannerName?: string
}

export function ReportPdfDocument({ data, vendorRatings, type, plannerName }: PdfDocProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>EventGrid: {data.event?.name || 'Event Report'}</Text>
        <Text style={styles.headerMeta}>
          {type === 'internal' ? 'Internal Report' : 'Client Report'} &middot;{' '}
          {data.event?.event_date ? new Date(data.event.event_date).toLocaleDateString('en-GB') : ''}
          {plannerName ? ` &middot; Prepared by ${plannerName}` : ''}
        </Text>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Attendance</Text>
          <View style={styles.row}><Text style={styles.label}>Guests Invited</Text><Text style={styles.value}>{data.guestCount}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Checked In</Text><Text style={styles.value}>{data.checkedIn}</Text></View>
        </View>

        {type === 'internal' && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Financial Summary</Text>
            <View style={styles.row}><Text style={styles.label}>Total Budget</Text><Text style={styles.value}>₦{(data.totalBudget / 100).toLocaleString('en-NG')}</Text></View>
          </View>
        )}

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Vendors ({data.vendorCount})</Text>
          {vendorRatings.map((vr) => (
            <View key={vr.id} style={styles.row}>
              <Text style={styles.label}>{vr.name} ({vr.category})</Text>
              <Text style={styles.ratingStar}>{'★'.repeat(vr.rating)}{'☆'.repeat(5 - vr.rating)}</Text>
            </View>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Issues</Text>
          <View style={styles.row}><Text style={styles.label}>Total Issues</Text><Text style={styles.value}>{data.issues.length}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Resolved</Text><Text style={styles.value}>{data.issuesResolved}</Text></View>
          {data.issues.filter((i) => i.lessons_learned).map((i) => (
            <View key={i.id} style={{ marginBottom: 4 }}>
              <Text style={{ fontSize: 10, fontWeight: 'bold' }}>{i.title}</Text>
              <Text style={{ fontSize: 9, color: '#666' }}>Lesson: {i.lessons_learned}</Text>
            </View>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Phase Progress</Text>
          {data.phases.map((p) => (
            <View key={p.id} style={styles.phaseItem}>
              <View style={[styles.phaseDot, { backgroundColor: p.status === 'completed' ? '#22c55e' : '#d1d5db' }]} />
              <Text style={{ fontSize: 10 }}>Phase {p.phase_number}: {p.phase_name}</Text>
            </View>
          ))}
        </View>

        <Text style={styles.footer}>
          Generated by EventGrid &middot; {new Date().toLocaleDateString('en-GB')}
        </Text>
      </Page>
    </Document>
  )
}
