ALTER TABLE public.seating_tables ADD COLUMN IF NOT EXISTS x DOUBLE PRECISION DEFAULT 0;
ALTER TABLE public.seating_tables ADD COLUMN IF NOT EXISTS y DOUBLE PRECISION DEFAULT 0;
ALTER TABLE public.seating_tables ADD COLUMN IF NOT EXISTS width DOUBLE PRECISION DEFAULT 120;
ALTER TABLE public.seating_tables ADD COLUMN IF NOT EXISTS height DOUBLE PRECISION DEFAULT 80;
ALTER TABLE public.seating_tables ADD COLUMN IF NOT EXISTS rotation DOUBLE PRECISION DEFAULT 0;
